export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "mysql://3H3qNMVuMPNQvMbD:yFhBMEPJFxMnJBhA@gateway03.us-east-1.prod.aws.tidbcloud.com:4000/mLbezbk5ZAEXFd46ngs4DG?ssl={\"rejectUnauthorized\":true}",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  ownerEmail: process.env.OWNER_EMAIL ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  hypUsername: process.env.HYP_USERNAME ?? "",
  hypPassword: process.env.HYP_PASSWORD ?? "",
  hypTerminalNumber: process.env.HYP_TERMINAL_NUMBER ?? "",
  hypApiToken: process.env.HYP_API_TOKEN ?? "",
};
