// Auto-generated from Articles.tsx — DO NOT EDIT MANUALLY
// Run rebuild_articles_data2.py to regenerate

export interface ArticleOGData {
  slug: string;
  title: string;
  excerpt: string;
  img: string;
  audioSrc?: string;
  category: string;
  date: string;
  readTime: string;
}

export const ARTICLES: ArticleOGData[] = [
  {
    slug: "perek-22-tanya",
    title: "פרק כ\"ב בתניא – \"אני ואפסי עוד\"",
    excerpt: `הקדמה: פרק כ"ב בתניא הוא המשך ישיר לפרק כ"א, ויחד הם מהווים יחידה רעיונית שלמה. בפרק כ"א ביאר אדמו"ר הזקן כי דיבורו של הקב"ה אינו דומה לדיבורו של האדם - שכן דיבור האדם מובדל ממנו לאחר יציאתו מפיו, ואי...`,
    img: "https://www.nativ-lamishpacha.com/manus-storage/perek22_v2_1516179a.jpg",
    audioSrc: "/manus-storage/perek22_full_aba37547.wav",
    category: "פרקים בתניא",
    date: "יוני 29, 2026",
    readTime: "15 דקות קריאה",
  },
  {
    slug: "girushin-bhaskhama",
    title: "גירושין בהסכמה – הדרך המכבדת לסיום קשר הנישואין",
    excerpt: `גירושין בהסכמה מהווים חלופה מכבדת, אחראית ויעילה להליך משפטי ממושך. במקום לנהל מאבק בבית המשפט, בני הזוג בוחרים לנהל דיאלוג ענייני, להגיע להסכמות משותפות ולסיים את הקשר מתוך כבוד הדדי...`,
    img: "https://www.nativ-lamishpacha.com/manus-storage/girushin_haskhama_cf_2880e19a.webp",
    audioSrc: "/manus-storage/girushin_haskhama_5fcaa444.wav",
    category: "גישור ויישוב סכסוכים",
    date: "יוני 28, 2026",
    readTime: "",
  },
  {
    slug: "hasiyon-hagishur",
    title: "חסיון בהליך הגישור",
    excerpt: `על הליך הגישור חל חסיון מלא. החסיון חל על כל הנאמר בתהליך — הן על ידי הצדדים ביניהם לבין עצמם, והן יחד עם המגשר. מטרתו לאפשר לצדדים לנהל משא-ומתן חופשי ללא חשש שדבריהם ישמשו כנגדם בעתיד...`,
    img: "https://www.nativ-lamishpacha.com/manus-storage/hasiyon_article_823a6818.jpg",
    audioSrc: "/manus-storage/hasiyon_article_26d11cc5.wav",
    category: "גישור ויישוב סכסוכים",
    date: "יוני 28, 2026",
    readTime: "",
  },
  {
    slug: "munachim-psikologia-yehudit",
    title: "מונחים בפסיכולוגיה יהודית",
    excerpt: `צמצום בפסיכולוגיה יהודית המושג "צמצום" מגיע מהקבלה, בעיקר מתורת האר"י. במקור הקבלי, הצמצום מתאר רעיון עמוק מאוד: כדי שיהיה מקום לעולם – האינסוף "צמצם" את עצמו. כלומר, האלוהות זה כמובן רעיון מיסטי,...`,
    img: "https://www.nativ-lamishpacha.com/manus-storage/pesishlogya_3a0c33e5.png",
    audioSrc: "/manus-storage/OnyirlBlkKEVrbtN.wav",
    category: "פסיכולוגיה יהודית",
    date: "יוני 6, 2026",
    readTime: "",
  },
  {
    slug: "shlavey-hagishur",
    title: "שלבי תהליך הגישור",
    excerpt: `תהליך הגישור הוא הליך מובנה ליישוב סכסוכים, שבו צד שלישי ניטרלי מסייע לצדדים לנהל דיאלוג, להבין את צורכיהם ולהגיע להסכמות משותפות. על פי פישר, יורי ופטון (Fisher, Ury & Patton 2011), מטרת הגישור אינה...`,
    img: "https://www.nativ-lamishpacha.com/manus-storage/gishur_b6a5d06e.png",
    audioSrc: "/manus-storage/article_shlavey-hagishur_f8dd0e30.wav",
    category: "גישור ויישוב סכסוכים",
    date: "יוני 3, 2026",
    readTime: "",
  },
  {
    slug: "psikiatriya-vedat",
    title: "פסיכיאטריה ודת",
    excerpt: `מאמר העוסק ביחסים בין פסיכיאטריה לדת מנקודת מבט יהודית. הרב וולבא מציג תובנות מעמיקות על הקשר בין בריאות הנפש לאמונה הדתית...`,
    img: "https://www.nativ-lamishpacha.com/manus-storage/meir-1024x1024_62f0207f.png",
    audioSrc: "/manus-storage/article_psikiatriya-vedat_929f297c.wav",
    category: "פסיכולוגיה יהודית",
    date: "יוני 3, 2026",
    readTime: "",
  },
  {
    slug: "gesher-hashalom",
    title: "גשר השלום — הגישור ככלי מחזיק ברכה",
    excerpt: `גשר השלום – הגישור ככלי מחזיק ברכה\\\\n\\\\nהגישור ויישוב סכסוכים לאור ערך השלום\\\\n\\\\nאמרו חז\\\\"ל: \\\\"לא מצא הקדוש ברוך הוא כלי מחזיק ברכה לישראל אלא השלום, שנאמר: 'ה' עֹז לעמו ייתן, ה' יברך את עמו...`,
    img: "https://www.nativ-lamishpacha.com/manus-storage/shalom_6074c0aa.png",
    audioSrc: "/manus-storage/article_gesher-hashalom_38998511.wav",
    category: "גישור ויישוב סכסוכים",
    date: "נובמבר 11, 2020",
    readTime: "",
  },
  {
    slug: "yitronot-hagishur",
    title: "יתרונות הגישור ככלי ליישוב סכסוכים",
    excerpt: `חילוקי דעות המובילים לסכסוכים הם סיטואציות נורמליות כחלק ממהלך החיים שלנו. הם יכולים להתרחש בכל זמן נתון, בכל מקום, ועם כל אחד. קיימות מספר אפשרויות לפתרון סכסוכים כאשר אחת הדרכים הטובות ביותר היא...`,
    img: "https://www.nativ-lamishpacha.com/manus-storage/gishur_4_d4527c4d.jpg",
    audioSrc: "/manus-storage/QKiJbxPyXMdwxtzk.wav",
    category: "גישור ויישוב סכסוכים",
    date: "נובמבר 10, 2020",
    readTime: "",
  },
  {
    slug: "kashyim-zihuy-intresim",
    title: "קשיים בזיהוי אינטרסים בהליך הגישור",
    excerpt: `קשיים בזיהוי אינטרסים בהליך הגישור ברוב המקרים בעימות בהליך גישור, הצדדים אינם מציגים באופן ברור ושקוף את האינטרסים שלהם. ישנם מספר סיבות לכך: חוסר מודעות לאינטרסים: כלומר הצדדים אינם יודעים לזהות...`,
    img: "https://www.nativ-lamishpacha.com/manus-storage/puzzle_be12d8ab.jpg",
    audioSrc: "/manus-storage/yZHQEfbuCJISTLQw.wav",
    category: "גישור ויישוב סכסוכים",
    date: "אוגוסט 11, 2020",
    readTime: "",
  },
  {
    slug: "amadot-intresim-shkarim",
    title: "עמדות אינטרסים ושקרים",
    excerpt: `המעורבות של מגשר אינה מבטיחה את כנות הצדדים לגבי האינטרסים שלהם. שקרים גם יכולים לבוא לידי ביטוי כאשר צד מבין בצורה לא נכונה את האינטרסים על מנת לשכנע את הצד השני שרק פתרון מסוים יספק אותו.`,
    img: "https://www.nativ-lamishpacha.com/manus-storage/moznaim_2_d888f84f.jpg",
    audioSrc: "/manus-storage/article_amadot-intresim-shkarim_9c96b808.wav",
    category: "גישור ויישוב סכסוכים",
    date: "אוגוסט 11, 2020",
    readTime: "",
  },
  {
    slug: "zihuy-intresim-kabala-haskama",
    title: "זיהוי אינטרסים קבלה והסכמה",
    excerpt: `זיהוי אינטרסים:המפתח לקבלה, להסכמה ולהתקדמות במשא ומתן מבוא:אחד האתגרים המרכזיים בגישור ובמשא ומתן הוא המעבר מעיסוק ב"עמדות" לעיסוק ב"אינטרסים". בעוד שעמדה היא מה שהצד אומר שהוא רוצה, האינטרס הוא...`,
    img: "https://www.nativ-lamishpacha.com/manus-storage/gishor_f799b954.png",
    audioSrc: "/manus-storage/BBQcayVpTcTlVSXn.wav",
    category: "גישור ויישוב סכסוכים",
    date: "אוגוסט 11, 2020",
    readTime: "",
  },
  {
    slug: "mahalakhim-akifim",
    title: "מהלכים עקיפים לחשיפת אינטרסים",
    excerpt: `להלן בחינה של תהליכים לחשיפת אינטרסים\\\\n\\\\nמגשרים משתמשים במיומנויות תקשורת על מנת לזהות אינטרסים כמו:\\\\n\\\\nהקשבה פעילה, שיקוף, ניסוח מחדש, תמצות, הכללה, חלוקה לקטעים או תבניות.\\\\n\\\\nכאשר משתמשים...`,
    img: "https://www.nativ-lamishpacha.com/manus-storage/hand_wood_b5892c6a.jpg",
    audioSrc: "/manus-storage/article_mahalakhim-akifim_8102f1be.wav",
    category: "גישור ויישוב סכסוכים",
    date: "אוגוסט 11, 2020",
    readTime: "",
  },
  {
    slug: "mahalakhim-yesharim",
    title: "מהלכים ישירים לחשיפת האינטרסים",
    excerpt: `מהלכים ישירים הם כלים שמגשרים וצדדים במשא ומתן משתמשים בהם כדי לחשוף באופן מפורש את האינטרסים שעומדים מאחורי העמדות — שאלות ישירות, הקשבה פעילה, שיקוף וזיהוי צרכים...`,
    img: "https://www.nativ-lamishpacha.com/manus-storage/gihur_55_40b55101.jpg",
    audioSrc: "/manus-storage/article_mahalakhim-yesharim_3bc072dd.wav",
    category: "גישור ויישוב סכסוכים",
    date: "אוגוסט 11, 2020",
    readTime: "",
  },
  {
    slug: "matzavey-zihuy-intresim",
    title: "מצבי זיהוי אינטרסים: המפתח לקבלה, להסכמה ולהתקדמות במשא ומתן",
    excerpt: `אחד האתגרים המרכזיים בגישור ובמשא ומתן הוא המעבר מעיסוק ב"עמדות" לעיסוק ב"אינטרסים". כאשר מגשר מסייע לצדדים לזהות את האינטרסים האמיתיים שלהם, נפתחות אפשרויות חדשות לפתרון, גם במצבים שנראים בתחילה כ"מבוי סתום"...`,
    img: "https://www.nativ-lamishpacha.com/manus-storage/gishur_222_7c863462.jpg",
    audioSrc: "/manus-storage/FcDXXtgDXmheRsIt.wav",
    category: "גישור ויישוב סכסוכים",
    date: "אוגוסט 11, 2020",
    readTime: "",
  },
  {
    slug: "gishot-produktiviot",
    title: "גישות פרודוקטיביות (בעלות יכולת לייצר ולהפיק)",
    excerpt: `הבנה של אינטרסים של הצד שכנגד מסייעת להביא לתוצאות טובות יותר. אפשר להקל על זיהוי אינטרסים ע"י שימוש ופתוח גישות פתוחות לכך כמו: 1. אמונה שלכל הצדדים יש אינטרסים וצרכים החשובים להם. 2. אמונה שתפרון...`,
    img: "https://www.nativ-lamishpacha.com/manus-storage/gishur_1_5945dc18.jpg",
    audioSrc: "/manus-storage/article_gishot-produktiviot_94d2b66b.wav",
    category: "גישור ויישוב סכסוכים",
    date: "אוגוסט 11, 2020",
    readTime: "",
  },
  {
    slug: "halich-gerushin-brabanut",
    title: "הליך גירושין ברבנות",
    excerpt: `הליך גירושין ברבנות בישראל כפופים לדין האישי שחל על הצדדים. על פי החוק, כאשר מדובר על גירושין בין בני זוג יהודים, רק לבית הדין הרבני יש את הסמכות להתיר את הנישואין ולאשר את מתן וקבלת גט. זהו אפוא...`,
    img: "https://www.nativ-lamishpacha.com/manus-storage/Giroshien-1_07e74250.png",
    audioSrc: "/manus-storage/article_halich-gerushin-brabanut_aecb1aa5.wav",
    category: "משפטיים",
    date: "אוגוסט 3, 2020",
    readTime: "",
  },
  {
    slug: "yeutz-zugi-trom-gerushin",
    title: "ייעוץ זוגי טרום לגירושין",
    excerpt: `לרוב האנשים גירושין זה אחד האירועים הטראומטיים ביותר בחיים. גם כאשר נישואין מגיעים לסופם, רבים מגלים שההחלטה לפרידה מלווה בתהליך ארוך וכואב של קבלה והשלמה ולא פחות חשוב – הגירושין ממשיכים להשפיע על שני בני הזוג ועל ילדיהם זמן רב לאחר מכן.`,
    img: "https://www.nativ-lamishpacha.com/manus-storage/yeutz_legerushin_da9179cf.jpg",
    audioSrc: "/manus-storage/article_yeutz-zugi-trom-gerushin_4ce2402a.wav",
    category: "טיפול זוגי בנישואין",
    date: "אוגוסט 3, 2020",
    readTime: "",
  },
  {
    slug: "gviyat-ketuba-mugzemet",
    title: "גביית כתובה מוגזמת",
    excerpt: `במאמר זה נעסוק בנושא רגיש וחשוב אשר מעסיק רבים מדייני בתי הדין הרבניים בכל מיני קונסטלציות שונות ומגוונות. "גביית כתובה מוגזמת ומופרזת שלעיתים הסכום הנקוב בה מסתכם במיליוני שקלים" בעיקר נתמקד בשאלה...`,
    img: "https://www.nativ-lamishpacha.com/manus-storage/ketoba_6711d876.png",
    audioSrc: "/manus-storage/article_gviyat-ketuba-mugzemet_c8a8fe39.wav",
    category: "הלכתיים - בין בני זוג",
    date: "אוגוסט 3, 2020",
    readTime: "",
  },
  {
    slug: "mezonot-zmaniyim",
    title: "מזונות זמניים בבית הדין",
    excerpt: `רבים מהמתגרשים בוחרים בדרך הקלה שהיא הסכם גירושין, המכיל את כל הפרמטרים הנדרשים כולל מזונות ומזונות זמניים. אך ישנם פעמים שאין מנוס מפאת, שנשללה האפשרות ליצור הסכם גירושין המוסכם על הצדדים. ונאלצים...`,
    img: "https://www.nativ-lamishpacha.com/manus-storage/gold_bridge_f0145645.jpg",
    audioSrc: "/manus-storage/ThRWRxuVWHuMWcMn.wav",
    category: "משפטיים",
    date: "יולי 22, 2020",
    readTime: "",
  },
  {
    slug: "gishur-min-hatorah",
    title: "צדק משפט וגישור מהתורה",
    excerpt: `בתנ"ך נזכרים המושגים צדק, משפט, דין, יושר, מישור, מישרים. התורה מעודדת הליך נוסף בשם משפט יושר: משפט המתקבל בהסכמה על-ידי שני הצדדים ומהווה סוג של פשרה ביניהם, או גישור כפתרון יצירתי לישוב הסכסוך...`,
    img: "https://www.nativ-lamishpacha.com/manus-storage/gishur-torah_4a94fc80.jpg",
    audioSrc: "/manus-storage/article_gishur-min-hatorah_7fbf4fa1.wav",
    category: "גישור ויישוב סכסוכים",
    date: "יוני 22, 2026",
    readTime: "",
  },
  {
    slug: "gishur-keli-tipuli",
    title: "גישור ככלי טיפולי בישוב סכסוכים בין בני זוג",
    excerpt: `גישור הוא כלי המשמש לישוב סכסוכים, שיכול להוות כלי טיפולי אפקטיבי לטיפול במשבר ספציפי מוגדר גבולות, הנוצר בין בני זוג. גישור זוגי מציע דרך ליציאה מהמבוי הסתום בו נמצאים הצדדים, על ידי פתרון נקודות המחלוקת...`,
    img: "https://www.nativ-lamishpacha.com/manus-storage/TlD4G534kofe_717ecc28.jpg",
    audioSrc: "/manus-storage/article-gishur-tipuli_ddd5bfdf.wav",
    category: "גישור ויישוב סכסוכים",
    date: "יוני 24, 2026",
    readTime: "",
  },
  {
    slug: "gishur-min-hatorah-2",
    title: "צדק, משפט וגישור מהתורה",
    excerpt: `בתנ"ך נזכרים המושגים צדק, משפט, דין, יושר, מישור, מישרים. התורה מעודדת הליך בשם משפט יושר: משפט המתקבל בהסכמה על-ידי שני הצדדים ומהווה סוג של פשרה ביניהם, או גישור כפתרון יצירתי לישוב הסכסוך...`,
    img: "https://www.nativ-lamishpacha.com/manus-storage/M4rPOV2hrgXM_f121d1b5.jpg",
    audioSrc: "/manus-storage/article-gishur-torah_f55948e9.wav",
    category: "גישור ויישוב סכסוכים",
    date: "יוני 24, 2026",
    readTime: "",
  },
  {
    slug: "gishur-tipuli-2",
    title: "גישור טיפולי ככלי לישוב סכסוכים",
    excerpt: `גישור טיפולי הוא גישה מיוחדת לפתרון סכסוכים המשלבת עקרונות טיפוליים עם תהליך הגישור. הוא מכיר בכך שסכסוכים כרוכים לא רק בבעיות מעשיות אלא גם בממדים רגשיים ופסיכולוגיים...`,
    img: "https://www.nativ-lamishpacha.com/manus-storage/CS6J0D6P8c4U_62f30112.jpg",
    audioSrc: "/manus-storage/article-gishur-tipuli2_87dd11b1.wav",
    category: "גישור ויישוב סכסוכים",
    date: "יוני 24, 2026",
    readTime: "",
  },
  {
    slug: "avnei-derech-bagishur",
    title: "אבני דרך בהליך הגישור",
    excerpt: `מאמר זה מביא שש עצות שהן בבחינת לחם חוקם של מגשרים ותיקים, ואבני דרך מועילות עבור מגשרים צעירים בראשית דרכם — מהפרדת אנשים מבעיות, דרך ניהול רגשות ועד הבעת אמפתיה.`,
    img: "https://www.nativ-lamishpacha.com/manus-storage/photo_1521791136064_1ab5fd00.jpg",
    audioSrc: "/manus-storage/article-avnei-derech_1214ebd3.wav",
    category: "גישור ויישוב סכסוכים",
    date: "יוני 24, 2026",
    readTime: "",
  },
  {
    slug: "ikronot-bagishur",
    title: "עקרונות בגישור וישוב סכסוכים",
    excerpt: `עקרונות יסוד בגישור וישוב סכסוכים — הפרדת רגשות מעניינים, קביעת יעדים מתוכננים, זיהוי הכוחות המנהלים אותנו, ועיקרון ואהבת לרעיך כמוך בתהליך הגישור.`,
    img: "https://www.nativ-lamishpacha.com/manus-storage/photo_1450101499163_abbbf16e.jpg",
    audioSrc: "/manus-storage/article-ikronot_ea3b993b.wav",
    category: "גישור ויישוב סכסוכים",
    date: "יוני 24, 2026",
    readTime: "",
  },
  {
    slug: "gishoot-psych-yehudit",
    title: "גישות קיימות בעולם הפסיכולוגיה היהודית",
    excerpt: `סקירה מקצועית של גישות מרכזיות בפסיכולוגיה היהודית — מרוטנברג ותנועת המוסר ועד גישות אינטגרטיביות עכשוויות המשלבות עבודה נפשית עם עומק רוחני ומוסרי.`,
    img: "https://www.nativ-lamishpacha.com/manus-storage/psych-img2_9e388e39.jpg",
    audioSrc: "/manus-storage/psych2-full_ff7a8352.wav",
    category: "פסיכולוגיה יהודית",
    date: "יוני 24, 2026",
    readTime: "",
  },
  {
    slug: "psych-yehudit-mekorot",
    title: "פסיכולוגיה יהודית מן המקורות",
    excerpt: `יסודות הפסיכולוגיה היהודית — מבנה הנפש, כוחותיה, דרכי האבחון והטיפול על פי מקורות התורה, החסידות ותורת המוסר.`,
    img: "https://www.nativ-lamishpacha.com/manus-storage/psych-img3_b9edaf7d.jpg",
    audioSrc: "/manus-storage/psych3-full_61a411ff.wav",
    category: "פסיכולוגיה יהודית",
    date: "יוני 24, 2026",
    readTime: "",
  },
  {
    slug: "cbt-yahadut-chassidut",
    title: "פסיכולוגיה קוגניטיבית־התנהגותית בראי היהדות והחסידות",
    excerpt: `מפגש מרתק בין הפסיכולוגיה הקוגניטיבית־התנהגותית (CBT) לבין עולמה של היהדות והחסידות — השמחה, "מוח שליט על הלב", ורחמים עצמיים לפי רבי נחמן מברסלב.`,
    img: "https://www.nativ-lamishpacha.com/manus-storage/psych-img4_5f92858c.jpg",
    audioSrc: "/manus-storage/psych4-full_901f729b.wav",
    category: "פסיכולוגיה יהודית",
    date: "יוני 24, 2026",
    readTime: "",
  },
  {
    slug: "shalom-bayit-beshituf-peula",
    title: "שלום בית בשיתוף פעולה",
    excerpt: `גישה מתקדמת לטיפול במשבר זוגי — "גירושין בשיתוף פעולה" ככלי לשלום בית. צוות מקצועי של משפטנים, כלכלנים ומטפלים רגשיים עובד יחד לטובת כל בני המשפחה.`,
    img: "https://www.nativ-lamishpacha.com/manus-storage/shalom_bayit_1ec4b53e.webp",
    audioSrc: "/manus-storage/shalom-bayit_090208ba.wav",
    category: "טיפול זוגי בנישואין",
    date: "יוני 24, 2026",
    readTime: "",
  },
];

export const ARTICLES_BY_SLUG: Record<string, ArticleOGData> = Object.fromEntries(
  ARTICLES.map(a => [a.slug, a])
);
